0.3.17

diff --git a/.github/workflows/napi.yml b/.github/workflows/napi.yml
--- a/.github/workflows/napi.yml
+++ b/.github/workflows/napi.yml
@@ -62,15 +62,15 @@ jobs:
           # Avoid running man-db triggers, which sometimes takes several minutes
           # to complete.
           sudo apt-get remove --purge -y man-db
-          # Install clang-14, lld-14, and debootstrap.
-          echo "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-14 main" |
-            sudo dd of=/etc/apt/sources.list.d/llvm-toolchain-focal-14.list
+          # Install clang-15, lld-15, and debootstrap.
+          echo "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-15 main" |
+            sudo dd of=/etc/apt/sources.list.d/llvm-toolchain-focal-15.list
           curl https://apt.llvm.org/llvm-snapshot.gpg.key |
             gpg --dearmor                                 |
           sudo dd of=/etc/apt/trusted.gpg.d/llvm-snapshot.gpg
           sudo apt-get update
-          sudo apt-get install --no-install-recommends debootstrap     \
-                                                       clang-14 lld-14
+          # this was unreliable sometimes, so try again if it fails
+          sudo apt-get install --no-install-recommends debootstrap clang-15 lld-15 || echo 'Failed. Trying again.' && sudo apt-get clean && sudo apt-get update && sudo apt-get install --no-install-recommends debootstrap clang-15 lld-15
           # Create ubuntu-16.04 sysroot environment, which is used to avoid
           # depending on a very recent version of glibc.
           # `libc6-dev` is required for building any C source files.
@@ -93,8 +93,8 @@ jobs:
           CARGO_PROFILE_RELEASE_LTO=false
           RUSTFLAGS<<__1
             -C linker-plugin-lto=true
-            -C linker=clang-14
-            -C link-arg=-fuse-ld=lld-14
+            -C linker=clang-15
+            -C link-arg=-fuse-ld=lld-15
             -C link-arg=--sysroot=/sysroot
             -C link-arg=-Wl,--allow-shlib-undefined
             -C link-arg=-Wl,--thinlto-cache-dir=$(pwd)/target/release/lto-cache
@@ -103,15 +103,15 @@ jobs:
           __1
           RUSTDOCFLAGS<<__1
             -C linker-plugin-lto=true
-            -C linker=clang-14
-            -C link-arg=-fuse-ld=lld-14
+            -C linker=clang-15
+            -C link-arg=-fuse-ld=lld-15
             -C link-arg=--sysroot=/sysroot
             -C link-arg=-Wl,--allow-shlib-undefined
             -C link-arg=-Wl,--thinlto-cache-dir=$(pwd)/target/release/lto-cache
             -C link-arg=-Wl,--thinlto-cache-policy,cache_size_bytes=700m
             ${{ env.RUSTFLAGS }}
           __1
-          CC=clang-14
+          CC=clang-15
           CFLAGS=-flto=thin --sysroot=/sysroot
           __0
 
